#!/bin/bash

shasum -c data/model.t7.sha1
retval=$?
if [ $retval -ne 0 ]; then
  if [ -f data/model.t7 ]; then
    echo "----------------Removing stale model file----------------"
    rm -f data/model.t7
  fi
  echo "----------------Downloading question-generation model----------------"
  wget https://s3.eu-central-1.amazonaws.com/idris-public-data/model.t7 -P data/
fi

echo "----------------Installing python requirements----------------"
pip3 install -r requirements.txt

echo "----------------Pulling corenlp and opennmt docker images----------------"
docker pull sld3/corenlp:3.6.0
docker pull sld3/opennmt:780979ab_distro20e52377

echo "----------------Running corenlp and opennmt servers----------------"
docker run -d --name corenlp2 -p 9000:9000 sld3/corenlp:3.6.0
opennmt_run_cmd="cd /root/opennmt && th tools/translation_server.lua \
  -host 0.0.0.0 -port 5556  -model /root/data/model.t7 -beam_size 12"
docker run -d --name opennmt2 -it -p 5556:5556 -v $(pwd)/data:/root/data sld3/opennmt:780979ab_distro20e52377 bash -c "$opennmt_run_cmd"
